# Generated by Django 2.2.2 on 2019-11-30 07:42

import datetime
from django.db import migrations
from django.utils.timezone import utc
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191130_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='tax',
            field=wagtail.core.fields.RichTextField(default=datetime.datetime(2019, 11, 30, 7, 42, 5, 640281, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
