# Generated by Django 2.2.2 on 2019-11-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191130_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='tax',
        ),
    ]
