# Generated by Django 2.2.2 on 2019-11-30 09:37

from django.db import migrations
import django_extensions.db.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('product', 'ref'), separator=''),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='tax',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
