# Generated by Django 2.2.2 on 2019-11-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_productvariant_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
