# Generated by Django 2.2.2 on 2019-11-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
