# Generated by Django 2.2.2 on 2019-11-30 10:28

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191130_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('product', 'ref', 'tax'), separator=''),
        ),
    ]
