# Generated by Django 2.2.2 on 2019-11-30 12:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191130_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='tax',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('product', 'ref', 'tax applied'), separator=''),
        ),
    ]
